# Generated by Django 5.0.6 on 2024-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
