# Generated by Django 5.0.6 on 2024-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_latitude_car_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(choices=[('2', '2 seats'), ('4', '4 seats'), ('6', '6 seats')], default=4),
            preserve_default=False,
        ),
    ]
