# Generated by Django 5.0.6 on 2024-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_car_seats_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make_and_model',
            field=models.CharField(choices=[('Perodua Myvi', 'Perodua Myvi'), ('Honda City', 'Honda City'), ('Toyota Vios', 'Toyota Vios'), ('Honda Civic', 'Honda Civic')], default='Honda City', max_length=50),
            preserve_default=False,
        ),
    ]
