# Generated by Django 5.0.6 on 2024-06-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_car_make_and_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make_and_model',
            field=models.CharField(choices=[('Porsche', 'Porsche'), ('Jaguar', 'Jaguar'), ('Supra', 'Supra'), ('Perodua Myvi', 'Perodua Myvi'), ('Honda City', 'Honda City'), ('Toyota Vios', 'Toyota Vios'), ('Honda Civic', 'Honda Civic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.CharField(choices=[('2', '2 seats'), ('4', '4 seats'), ('6', '6 seats')], max_length=2),
        ),
    ]
