# Generated by Django 5.0.6 on 2024-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_car_make_and_model_alter_car_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Porsche', 'Porsche'), ('Jaguar', 'Jaguar'), ('Supra', 'Supra'), ('Perodua Myvi', 'Perodua Myvi'), ('Honda City', 'Honda City'), ('Toyota Vios', 'Toyota Vios'), ('Honda Civic', 'Honda Civic')], default='SUV', max_length=50),
            preserve_default=False,
        ),
    ]
