# Generated by Django 5.0.6 on 2024-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan')], max_length=50),
        ),
    ]
