# Generated by Django 5.0.6 on 2024-10-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_status_alter_car_car_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PAYMENT_REQUIRED', 'Payment required'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PAYMENT_REQUIRED', max_length=20),
        ),
        migrations.CreateModel(
            name='Support_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_message_as_sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_message_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
