# Generated by Django 5.0.6 on 2024-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_booking_status_support_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PAYMENT_METHOD_REQUIRED', 'Payment method required'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PAYMENT_METHOD_REQUIRED', max_length=25),
        ),
    ]
