# Generated by Django 5.0.6 on 2024-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default='ONLINE', max_length=10),
            preserve_default=False,
        ),
    ]
