# Generated by Django 5.0.6 on 2024-11-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default=None, max_length=10, null=True),
        ),
    ]
