# Generated by Django 5.0.6 on 2024-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_ic_useraccount_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='verified_details',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='ic',
            field=models.FileField(upload_to='ic/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='licence',
            field=models.FileField(upload_to='licence/'),
        ),
    ]
