# Generated by Django 5.0.6 on 2024-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_verified_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.TextField(default='john doe'),
            preserve_default=False,
        ),
    ]
