# Generated by Django 5.0.6 on 2024-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
